POST https://localhost:8081/api/category/add
Content-Type: application/json

{
  "nameUz": "ichimliklar",
  "nameRu": "drinks",
  "parentCategory": null
}

###
GET https://localhost:8081/api/category/1
\
###
PUT http://localhost:8081/api/categeory/1
Content-Type: application/json
Accept-Language: uz

{
  "id": 1,
  "nameUz": "ichimliklar",
  "nameRu": "drinks"
}
###
DELETE http://localhost:8081/api/categeory/1

###
POST http://localhost:8081/api/categeory/list

