package uz.pdp.appproduct.dto.enums;


public enum PermissionEnum  {

    ADD_CATEGORY,
    ADD_PRODUCT,
    GET_PRICE_FOR_DELIVERY,
    GET_ALL_PRICES_FOR_DELIVERIES,
    ADD_PRICE_FOR_DELIVERY,
    EDIT_PRICE_FOR_DELIVERY,
    DELETE_PRICE_FOR_DELIVERY,
    DELETE_ALL_PRICES_FOR_DELIVERIES,
    EDIT_PRODUCT,
    EDIT_ORDER,
    ADD_ORDER,
    GET_ORDER_FOR_COURIER,
    EDIT_STATUS,
    GET_ORDER, SHOW_STATISTICS
}
