POST localhost:8181/api/order/v1/order/save-mob-app
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIrOTk4OTMwODUwMjM2IiwiaWF0IjoxNjY0OTUwOTg2LCJleHAiOjE2NjUwMjI5ODZ9.KdDUir8xBMbt5R-_hH0R1E6zXKYyVG3VSkWTI-AXJRN0qtrqznGWNDMmeunOdkO_IsaGSLfsojiWvCCy3yx_6w

{
  "orderProductsDTOList": [
    {
      "productId": 1,
      "quantity": 2
    },
    {
      "productId": 1,
      "quantity": 1
    }
  ],
  "addressDTO": {
    "lat": 80.59,
    "lng": 40.57,
    "address": "t",
    "extraAddress": "i"
  },
  "paymentType": "CASH"
}

###
POST http://localhost:8180/api/v1/order/save-web
Content-Type: application/json


###
GET http://localhost/api/order/v1/order/list-by-status/DRAFT
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIrOTk4OTMwODUwMjM2IiwiaWF0IjoxNjY0OTUwOTg2LCJleHAiOjE2NjUwMjI5ODZ9.KdDUir8xBMbt5R-_hH0R1E6zXKYyVG3VSkWTI-AXJRN0qtrqznGWNDMmeunOdkO_IsaGSLfsojiWvCCy3yx_6w


###
GET http://localhost/api/order/v1/order/order-status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiIrOTk4OTMwODUwMjM2IiwiaWF0IjoxNjY0OTUwOTg2LCJleHAiOjE2NjUwMjI5ODZ9.KdDUir8xBMbt5R-_hH0R1E6zXKYyVG3VSkWTI-AXJRN0qtrqznGWNDMmeunOdkO_IsaGSLfsojiWvCCy3yx_6w


###
POST localhost/api/order/v1/order/
Content-Type: application/json

{}