POST http://localhost:8081/api/v1/order/save-mob-app
Content-Type: application/json

{
  "orderProductsDTOList": [
    {
      "productId": 1,
      "quantity": 4
    }
  ],
  "addressDTO": {
    "lat": 2.98,
    "lng": 40.65,
    "address": "test_fd392723d30c",
    "extraAddress": "test_f33c38dda40d"
  },
  "paymentType": "CLICK"
}


###
GET http://localhost:8081/api/v1/order/list-by-status/PAYMENT_WAITING
Content-Type: application/json

