POST http://localhost:8081/api/order/save-app
Content-Type: application/json

{
  "orderProductsDTOList": [
    {
      "productId": 75,
      "quantity": 4
    }
  ],
  "addressDTO": {
    "lat": 2.98,
    "lng": 40.65,
    "address": "test_fd392723d30c",
    "extraAddress": "test_f33c38dda40d"
  },
  "paymentType": "CLICK"
}