spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/order_parent
    username: postgres
    password: root123
#  kafka:
#    bootstrap-servers: localhost:9092
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka
  instance:
    hostname: localhost

telegram:
  webhook-path: "https://76e9-178-218-201-90.in.ngrok.io/api/order/v1/telegram"
  bot-name: "@maxway_deliverybot"
  bot-token: "5511026470:AAHT-D1EXn447o_DdGh5F0PfrAI-iV9DzSQ"