package uz.pdp.apporder.entity.enums;


public enum PermissionEnum {

    EDIT_ORDER,
    ADD_ORDER,
    GET_ORDER_FOR_COURIER,
    EDIT_STATUS,
    GET_ORDER, SHOW_STATISTICS,
    SHOW_STATISTICS,
    ACCEPTED_STATUS,
    COOKING_STATUS,
    READY_STATUS,
    SENT_STATUS,
    CLOSED_STATUS,
    REJECTED_STATUS, FINISHED_STATUS,
}
