bot:
  name: maxway_deliverybot
  token: 5511026470:AAHT-D1EXn447o_DdGh5F0PfrAI-iV9DzSQ


server:
  port: 8099

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 2002
  jpa:
    hibernate:
      ddl-auto: create

